--Step 1) Create Tables 
-- Create Customers Table
CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Phone VARCHAR2(15),
    Address VARCHAR2(200),
    CreatedDate DATE DEFAULT SYSDATE
);

-- Create Agents Table
CREATE TABLE Agents (
    AgentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100),
    Phone VARCHAR2(15),
    CommissionRate NUMBER(5, 2) DEFAULT 10
);

-- Create Destinations Table
CREATE TABLE Destinations (
    DestinationID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Country VARCHAR2(100) NOT NULL,
    Description VARCHAR2(500),
    Popularity NUMBER DEFAULT 0
);

-- Create TourPackages Table
CREATE TABLE TourPackages (
    PackageID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    DestinationID NUMBER REFERENCES Destinations(DestinationID),
    Description VARCHAR2(500),
    Price NUMBER(10, 2) NOT NULL,
    Duration NUMBER NOT NULL -- in days
);

-- Create Bookings Table
CREATE TABLE Bookings (
    BookingID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER REFERENCES Customers(CustomerID),
    PackageID NUMBER REFERENCES TourPackages(PackageID),
    BookingDate DATE DEFAULT SYSDATE,
    TotalAmount NUMBER(10, 2) NOT NULL,
    AgentID NUMBER REFERENCES Agents(AgentID),
    Status VARCHAR2(50) DEFAULT 'Pending'
);

-- Create Payments Table
CREATE TABLE Payments (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BookingID NUMBER REFERENCES Bookings(BookingID),
    PaymentDate DATE DEFAULT SYSDATE,
    Amount NUMBER(10, 2) NOT NULL,
    PaymentMethod VARCHAR2(50) CHECK (PaymentMethod IN ('Credit Card', 'Debit Card', 'UPI', 'Net Banking'))
);

-- Create Transport Table
CREATE TABLE Transport (
    TransportID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type VARCHAR2(50) CHECK (Type IN ('Flight', 'Bus', 'Train', 'Car', 'Helicopter', 'Boat', 'Bike', 'Metro', 'Tram', 'SUV')), 
    Capacity NUMBER NOT NULL,
    PricePerSeat NUMBER(10, 2) NOT NULL
);

-- Create Reviews Table
CREATE TABLE Reviews (
    ReviewID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER REFERENCES Customers(CustomerID),
    PackageID NUMBER REFERENCES TourPackages(PackageID),
    Rating NUMBER CHECK (Rating BETWEEN 1 AND 5),
    Comments VARCHAR2(1000),
    ReviewDate DATE DEFAULT SYSDATE
);

--Insertion
-- Insert Customers
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Alice Johnson', 'alice@gmail.com', '1234567890', '123 Elm Street');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Bob Smith', 'bob@gmail.com', '9876543210', '456 Oak Avenue');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Charlie Adams', 'charlie@gmail.com', '5551234567', '789 Maple Lane');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('David Brown', 'david@gmail.com', '4445556666', '22 Pine Street');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Eve White', 'eve@gmail.com', '7778889999', '88 Birch Road');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Frank Green', 'frank@gmail.com', '1112223333', '15 Cedar Street');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Grace Miller', 'grace@gmail.com', '9998887777', '99 Spruce Lane');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Hank Wilson', 'hank@gmail.com', '3334445555', '43 Palm Avenue');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Ivy Carter', 'ivy@gmail.com', '8887776666', '27 Maple Drive');
INSERT INTO Customers (Name, Email, Phone, Address) VALUES ('Jack Taylor', 'jack@gmail.com', '5556667777', '76 Cherry Lane');

-- Insert Destinations
INSERT INTO Destinations (Name, Country, Description) VALUES ('Paris', 'France', 'The city of light and love.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Maldives', 'Maldives', 'Tropical paradise with white sandy beaches.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Tokyo', 'Japan', 'A blend of tradition and modernity.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('New York', 'USA', 'The city that never sleeps.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Sydney', 'Australia', 'A coastal city with iconic landmarks.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Dubai', 'UAE', 'Luxury and modern architecture.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('London', 'UK', 'Rich history and culture.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Rome', 'Italy', 'Home to ancient ruins and art.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Bangkok', 'Thailand', 'Vibrant nightlife and temples.');
INSERT INTO Destinations (Name, Country, Description) VALUES ('Cape Town', 'South Africa', 'Natural beauty and rich history.');

-- Insert Tour Packages
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Romantic Paris Getaway', 1, '5-day tour of Paris', 1200.00, 5);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Maldives Honeymoon Special', 2, '7-day Maldives package', 3000.00, 7);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Tokyo Explorer', 3, '10-day tour of Tokyo and surrounding areas', 2000.00, 10);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('New York Adventure', 4, '7-day tour of New York', 1800.00, 7);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Sydney Coastal Experience', 5, '6-day tour of Sydney', 1500.00, 6);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Dubai Luxury Escape', 6, '4-day tour of Dubai', 2500.00, 4);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('London Heritage Tour', 7, '5-day tour of London', 1700.00, 5);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Roman Holiday', 8, '3-day tour of Rome', 1300.00, 3);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Bangkok Nightlife Special', 9, '5-day tour of Bangkok', 1400.00, 5);
INSERT INTO TourPackages (Name, DestinationID, Description, Price, Duration) VALUES ('Cape Town Scenic Getaway', 10, '7-day tour of Cape Town', 2000.00, 7);

-- Insert Agents
INSERT INTO Agents (Name, Email, Phone) VALUES ('TravelX Agent', 'agent@travelx.com', '1122334455');
INSERT INTO Agents (Name, Email, Phone) VALUES ('ExploreMore Agent', 'agent2@exploremore.com', '2233445566');
INSERT INTO Agents (Name, Email, Phone) VALUES ('Wanderlust Agent', 'agent3@wanderlust.com', '3344556677');
INSERT INTO Agents (Name, Email, Phone) VALUES ('Adventure Agent', 'agent4@adventure.com', '4455667788');
INSERT INTO Agents (Name, Email, Phone) VALUES ('LuxuryTours Agent', 'agent5@luxurytours.com', '5566778899');
INSERT INTO Agents (Name, Email, Phone) VALUES ('Global Explorer', 'agent6@globalexplorer.com', '6677889900');
INSERT INTO Agents (Name, Email, Phone) VALUES ('Holiday Planner', 'agent7@holidayplanner.com', '7788990011');
INSERT INTO Agents (Name, Email, Phone) VALUES ('EcoTraveler Agent', 'agent8@ecotraveler.com', '8899001122');
INSERT INTO Agents (Name, Email, Phone) VALUES ('Backpack Tours', 'agent9@backpacktours.com', '9900112233');
INSERT INTO Agents (Name, Email, Phone) VALUES ('Family Fun Agent', 'agent10@familyfun.com', '1011121314');

-- Insert Transport Options
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Flight', 180, 150.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Bus', 50, 25.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Train', 300, 50.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Car', 4, 100.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Helicopter', 6, 500.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Boat', 50, 75.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Bike', 2, 15.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Metro', 100, 10.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('Tram', 60, 20.00);
INSERT INTO Transport (Type, Capacity, PricePerSeat) VALUES ('SUV', 7, 200.00);

